### ISSUE TITLE
[Bug Report] Filza crash when installing Java Runtime .deb

### ISSUE THREAD

**Issue by DrSalt123** [PojavLauncherTeam/PojavLauncher_iOS#116]
I am on IPhone 8 running IOS 14.2 Jailbroken with CheckRa1in 0.12.2

**Next, describe the issue.**
Make sure to be as descriptive as possible. 
When i attempt to install the java runtime .deb file from the github page through filza, it crashes filza instantly

**Any files you want to send?**
I’ve tried looking for latestlog.txt but can’t find it in filza and the root search didn’t pick it up, can anyone tell me when to find it?

Help much appreciated :)

**Comment by admin-elvistrujanovic** [comment]
Why not just use this jailbreak method instead of CheckRa1in (of course, first save everything you've used so far with checkra1n and then select "Restore System" in your Checkra1n app. If your app isn't visible, rejailbreak your phone with Checkra1n and then it will be all fixed - Follow the instructions from that website) [https://github.com/raspberryenvoie/odysseyn1x]() - This jailbreak method will allow you to use Odyssey jailbreak instead of Checkra1n on your phone and then you can just easily install Java and the game itself with repo that you will get together with Sileo (instead of Cydia). If you don’t get it, you’ll be able to add it yourself.

**Comment by admin-elvistrujanovic** [comment]
If you have any problems, feel free to contact me via email "elvistrujanovic51@gmail.com". I'm here to help.

**Comment by DrSalt123** [comment]
Ah i didn’t realise odyssey was out for iphone 8 14.2 cheers!

Great work man, didn’t even think this was possible!! 👍🏼👍🏼

**Comment by khanhduytran0** [comment]
> Ah i didn’t realise odyssey was out for iphone 8 14.2 cheers!

Do you mean Taurine?
