### ISSUE TITLE
[F-Req]Alt Login Support

### ISSUE THREAD

**Issue by Eric120110** [PojavLauncherTeam/PojavLauncher_iOS#199]
To use this template:
* CHECK OTHER ISSUES and see if anyone else has requested the same functionality. We will close any duplicate requests.
* Don't delete any of the words between asterisks. 
* Add something descriptive to the title (ex. [F-Req] Controller Support)
* Follow all of the steps. If you do not provide an answer to each section in this template, the issue will be closed.

// Delete this line and the above text before submitting.

**Is your feature request related to a problem? Please describe.**
Give us some details into the problem, and how this affects it.
Hope there are more ways to log in.
**Describe the solution you'd like**
What do you want to see changed, added, or removed? Make sure to be specific.
Add Alt login in the login page.
**Describe alternatives you've considered**
Is there anything else you’ve thought of but crossed off? If so, tell us why.
Cannot connect to the server under offline login (not being kicked by the genuine verification, I have not tried Mojang and Microsoft login)
**Additional context**
Have a mock-up? Perhaps a template or set of files. Share them here!
Device: iPhone 6s iOS 12.4 unc0ver
**Make sure you’ve dine the following:**
- [ ] Provided a clear description into what the feature request is
- [ ] (If applicable) provided an issue that this request would fix
- [ ] (If applicable) presented potential possibilities into adding this request
- [ ] (If applicable) Provided evidence such as a drawing, log file, file, etc. of what you wish to see reflected

**Comment by Doregon** [comment]
What do you mean by “Alt login”?

**Comment by Eric120110** [comment]
I mean u can use Mcleaks or the Thealtening to login.

**Comment by Doregon** [comment]
This option is unacceptable to use. Due to the fact that MCLeaks and Thealtening share free Minecraft premium accounts, we cannot support or condone these two or other services like these as they are committing piracy, which is something that we do not wish to associate with PojavLauncher. 

PojavLauncher simply puts the Minecraft executable on iOS, which means we have not modified any of the game's code and such we willingly follow along with the Terms of Use that Mojang has laid out. Offline accounts are allowed because Mojang hasn't yet said that they aren't, and Notch himself said to "Try before you buy". If legitimately buying Minecraft is not an option for you, then use an offline account. If neither are options for you, you are out of luck.
