### ISSUE TITLE
how much ram do I need to install iOS on my Samsung ram phone 

### ISSUE THREAD

**Issue by drybones64** [PojavLauncherTeam/PojavLauncher_iOS#202]
I want iOS so I can install more ram to play Minecraft for free

**Comment by Doregon** [comment]
1) iOS cannot be installed on non-Apple phones. If you heard that it was possible, then that source was scamming/fake.

2) Because you use an Android phone, you should take a trip over to https://github.com/PojavLauncherTeam/PojavLauncher, which is the Android project.

3) If by "free" you mean offline ratger than with a premium account, that's fine. If you mean free premium accounts or MCLeaks and similar services, we will not give you support for those.
