### ISSUE TITLE
[Question]modpacks??

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher_iOS#229]
If i paste a mod pack in the versions folder will it run ( i issued this before but i got an answer to android not ios)

**Comment by NotAHero04** [comment]
1. A reopen of your old issue, which is #208, is enough. The devs may close your issue due to duplication.
2. Some modpacks will have an option to download zip file which contains all of the mods and some configurations. Just unzip it and paste it to the mods folder.
3. If the modpack you want to install does not have the zip option, you have another option: try to download all mods and have some manual configurations.

**Comment by creyes200** [comment]
It didn't work i unzipped the modpack zip I downloaded from cursforge and pasted it into the mods folder but it didnt run it
