### ISSUE TITLE
[BUG URGENT] Can't Compile & Generate IPA on macOS 12.1 Monterey (I have all requirements)

### ISSUE THREAD

**Issue by lyoneofficial** [PojavLauncherTeam/PojavLauncher_iOS#309]
### Describe the bug

Impossibilty to build .IPA FILE

### The log file and images/videos

//

### Steps To Reproduce

```markdown
say error on first folder/file copying on build.sh
```

### Expected Behavior

//

### Platform

```markdown
- Device model: iPad 7th | For compiling macOS 12.1 Monterey
- iOS version: 15.1
- PojavLauncher version: //
```

**Comment by khanhduytran0** [comment]
Build log is not provided.

**Comment by Doregon** [comment]
I've just now pushed my changes to allow building the .ipa file with the Makefile. You need to download the latest artifact of the JRE from [here](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions), and extract it to `depends/jre` in order to build correctly. Ignore errors relating to libjstig.dylib.

If you're trying to build the .ipa file to run PojavLauncher on your iPad with iOS 15.1, warning you now that PojavLauncher will not run unjailbroken.

**Comment by lyoneofficial** [comment]
Is an error when first copying
