### ISSUE TITLE
[Question] What is the recommended amount of ram to play on servers like hypixel?

### ISSUE THREAD

**Issue by Galorlx** [PojavLauncherTeam/PojavLauncher_iOS#322]
### Ask the question here.

I was using it iPhone X 3gigs ram and it was playable but not the greatest for me I was just wondering for the next phone I buy

**Comment by artdeell** [comment]
Just get an Android with 6GB RAM and not on Mediatek/Snapdragon 4xx-6xx

**Comment by khanhduytran0** [comment]
> 3gigs ram 

> Just get an Android with 6GB RAM and not on Mediatek/Snapdragon 4xx-6xx

RAM doesn’t matter. 1.18.1 works with 699mb allocated so.

Snapdragon 4xx-6xx are still not well. There’s none in it that’s could go over A11. If you pick 8xx, it would be better.

> it was playable but not the greatest for me

How so?
With everything minimum in 1.16.5 on A9 (a 6 years ago CPU). I can get 25fps on server. With OptiFine, it’s even better. So check your video settings, like render distance. With A11, you’re supposed to get stable 60fps if settings are fine. 60fps is the maximum on your device because your screen refresh rate limits that. There’s no framerate limit on Android, but there’s no point to get over screen refresh rate.

**Comment by artdeell** [comment]
> Snapdragon 4xx-6xx are still not well. 

That's why i told to not get them. Only 7xx and up are good.

**Comment by crystall1nedev** [comment]
Closing issue as answer has been provided.
