### ISSUE TITLE
[Bug] Instant crash after starting minecraft while sideloading with a non jailbroken device

### ISSUE THREAD

**Issue by naturecodevoid** [PojavLauncherTeam/PojavLauncher_iOS#356]
### Describe the bug

After launching minecraft 1.18.2 with my microsoft account, the app instantly crashes.

### The log file and images/videos

```
:38:17.622 PojavLauncher[1368:138791] [MCDL] SHA1 passed for 1.18.json
:38:17.626 PojavLauncher[1368:138791] [Pre-init] Reading custom environment variables (custom_env.txt), opened=0
:38:17.626 PojavLauncher[1368:138791] [JavaLauncher] Beginning JVM launch
:38:17.626 PojavLauncher[1368:138791] [JavaLauncher] Attempting to change to Java 17 (actual might be higher)
:38:17.626 PojavLauncher[1368:138791] [JavaLauncher] Java 8 wasn't found on your device. Install Java 8 for more compatibility and the mod installer.
:38:17.626 PojavLauncher[1368:138791] [JavaLauncher] JAVA_HOME is now set to (null)
:38:17.695 PojavLauncher[1368:138785] *** Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'child view controller:<UICompatibilityInputViewController: 0x14b10e400> should have parent view controller:<SurfaceViewController: 0x14b056c00> but requested parent is:<UIInputWindowController: 0x14b026c00>'
*** First throw call stack:
(0x193769db8 0x18cc3fa68 0x193859760 0x196e031b4 0x196fbec0c 0x1970fb75c 0x196fbdffc 0x196fbdb34 0x196fbd318 0x196ecd4b4 0x196ecca24 0x196e560cc 0x196e53148 0x19752b1f0 0x19752ab5c 0x197529b54 0x196ece570 0x196e6c0f8 0x196c5cf44 0x196c59544 0x196cfdc88 0x1973ac728 0x196df0e4c 0x196df0d80 0x196df0c8c 0x196c8b530 0x19709657c 0x1937f1960 0x19377a200 0x1937db8ac 0x1937e0b04 0x1d701c360 0x196fef484 0x196fef0e8 0x102871b68 0x218a528f8)
libc++abi: terminating with uncaught exception of type NSException
```

### Steps To Reproduce

```markdown
1. Start 1.18.2 while sideloading without jailbreak
2. Observe crash
```

### Expected Behavior

I expect the game to function like normal and launch properly.

### Platform

```markdown
- Device model: iPad Air 4th gen
- iOS version: 16 Public Beta
- PojavLauncher version: Latest dev build
```

### Anything else?

I am currently sideloading with AltStore and AltJIT. My device is not jailbroken. I am willing to help with unjailbroken device support but there are no instructions for contributing.

**Comment by khanhduytran0** [comment]
If you read the log, you'll notice that it did not find any Java runtime. Why? Simply because you haven't provided one.

So, what is preventing us from releasing an IPA?
The game would run very slow (10x slower compared to installation with jailbreak) due to the absence of JIT (Just-in-time) compilation. You may found that some apps can enable JIT without jailbreaking, but they work different. Apple does not allow (debugger) JIT to run with both writable and executable at the same time, so jailbreak is used to break this restriction. Java requires this due to how the Java VM works: code compilation happens in a group of threads, while execution happens in other threads, at the same time. We are still trying to get around it. Until then, once JIT works, we will release PojavLauncher as an IPA package.

**Comment by khanhduytran0** [comment]
I have a proof-of-concept slow edition IPA, but it only includes Java 8 for now 
If you're interested in it, contact me in the Discord server.
