### ISSUE TITLE
add TrollStore support

### ISSUE THREAD

**Issue by gysok1337** [PojavLauncherTeam/PojavLauncher_iOS#381]
### Describe the request.

play without JIT using TrollStore

**Comment by khanhduytran0** [comment]
JIT is still required behind the scenes.
With jailbroken version, `dynamic-codesigning` entitlement is used to achieve RWX JIT.
The same could be applied for installing with TrollStore, but unfortunately, this entitlement is blocked since iOS 15.
Self-debug for W^X JIT could be possible by abusing other entitlements, I will look into it.

**Comment by khanhduytran0** [comment]
JIT should now be enabled automatically if installed through TrollStore.
