### ISSUE TITLE
[Bug] Hitting play results in a black screen

### ISSUE THREAD

**Issue by Earthys** [PojavLauncherTeam/PojavLauncher_iOS#413]
### Describe the bug

Installed this morning, black screen when i hit play that’s pretty much it

### Steps To Reproduce

```markdown
Press start
```

### Expected Behavior

Expect to show rhe minecraft menu

### Platform

```markdown
- Device model: Iphone11
- iOS version: 15.6.1
- PojavLauncher version: Unknown
```

**Comment by gysok1337** [comment]
you need to enable JIT

**Comment by SamZong233** [comment]
upload log please,diagnose cannot be done without log

**Comment by Earthys** [comment]
> 

Late reply but,
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/9947344/latestlog.txt)

**Comment by crystall1nedev** [comment]
Can you try using the release candidate we pushed out yesterday? I don't seem to be able to reproduce this on my end.

**Comment by esgie** [comment]
I think it is somehow related to not-fully-valid signature.
I am not Jailbroken; I have a paid developer account and do not use AltStore (I have no Mac and WiFi connection is extremely unstable under Windows, I am experimenting with AltServer-Linux and SideStore right now..), instead I prefer signing ipas offline using my exported p12/mobileprovision files using on-device solutions like Esign and GBox. That always worked, in particular for JIT enabled apps and for apps with fancy entitlements like VPN tunelling. But in case of PojavLauncher they both struggle to sign the app as intended. Under GBox, signing lasts only few seconds, which is far too short and some invalid app without icon and valid name is installed, it’s useless ofc; using Esign, signing lasts much longer, it looks like it succeeds but it fails exactly in the same way as described in this topic, e.g. all seems to work until I click Play, then black screen and nothing happens.
What worked for me was sideloading via appdb web service… then, the game is starting like intended.
Btw obviously, JIT had been enabled in all cases (tested with JitStreamer and Jitterbug).
Seems like PojavLauncher is damn difficult to sign properly due to all that Java stuff included and various third party signers can cause troubles.

**Comment by khanhduytran0** [comment]
iOS would have blocked install if one of Mach-O file had invalid signature.
You must make sure that there is `get-task-allow` entitlement in the signed ipa.
Also, maybe keep your eyes on Log output for a while to see if it’s loading anything.
