### ISSUE TITLE
[Bug] <@pre render error>

### ISSUE THREAD

**Issue by SYZYGYGAMER** [PojavLauncherTeam/PojavLauncher_iOS#428]
### Describe the bug

Render error when I use the launcher and check output it doesn’t end it just keeps on going and later it lags as fuxk

### Steps To Reproduce

```markdown
1start pojav 
2 start game(1.8.9 for me)
3 check out log output
```

### Expected Behavior

After you enter game log output shows @pre render and just keeps on goin it just keep going that error 

### Platform

```markdown
- Device model: 11
- iOS version: 1.16.1
- PojavLauncher version: 1.3
```

### Anything else?

Also after the latest update pojav launcher has become harder to use it just crashes sometimes without reason and some times I lag like I play in 1gb ram phone

**Comment by SYZYGYGAMER** [comment]
Pls fix its hard to play

**Comment by SYZYGYGAMER** [comment]
Also I can’t move any button to another place in custom control edit

**Comment by GaucovyAero** [comment]
no log provided, also, outdated version

**Comment by SYZYGYGAMER** [comment]
Also now I can’t disable Jit or it crashes before this update it was better

**Comment by SYZYGYGAMER** [comment]
![Uploading B788F81A-2F8D-4FEF-ACD4-46B40651B14A.png…]()

**Comment by SYZYGYGAMER** [comment]
It’s the latest

**Comment by khanhduytran0** [comment]
> it doesn’t end it just keeps on going and later it lags as

That’s how log works, it keeps going until you pause it, which you’re supposed to do before closing the Log Output screen. If you actually debug the game, you can leave it on, then clear logs if too much. However, in this case, you just play, no debug at all, so just don’t leave it on.

Because you keep Log Output ON, it keeps going in the background.

For the Pre-render error, it’s an issue in the rendering library, which seems only cause the game panorama to be minimized to a corner rather than being renderer fullscreen properly.

**Comment by InfernoNova9999** [comment]
Will the panorama issue get fixed? Its not broken on android

**Comment by khanhduytran0** [comment]
> Will the panorama issue get fixed? Its not broken on android

This might require updating ANGLE to latest (what concerns me is the compatibility of 1.17+), considering it.

**Comment by InfernoNova9999** [comment]
Have you ever tried it? I think you should make an experimental build and patch out the 1.17+ issues. If 1.17+ is broken, 1.16 and lower can use the newer version but 1.17+ could use the old version. Will that work?
