### ISSUE TITLE
[Bug] <Short description>

### ISSUE THREAD

**Issue by kidiron08** [PojavLauncherTeam/PojavLauncher_iOS#451]
### Describe the bug

Crash on open 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10233504/latestlog.txt)

### Steps To Reproduce

```markdown
1 start PojavLauncher
```

### Expected Behavior

I expect it to work properly

### Platform

```markdown
- Device model: I phone 7+
- iOS version: 15.7.1
- PojavLauncher version:1.3
```

**Comment by khanhduytran0** [comment]
Version 1.3-dev (1 year ago) is outdated. Update to latest version, [2.1](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/releases/tag/v2.1).

**Comment by kidiron08** [comment]
But now when I updated it’s giving me another error 
[Uploading latestlog.txt…]()

**Comment by khanhduytran0** [comment]
You should be using ipa instead of deb. deb package has check to prevent it from installing to rootless environment. (It seems like you made separate partition anyways so you may just modify the check to go ahead, however deb package is being removed in next release)
I recommend using something like AltStore, SideStore or TrollStore (see note below) to install.
* Note: TrollStore is originally made for iOS 14-15.5b4 and 15.6 betas only as it does **not** support permanent sign for other versions, so you can’t open installed app in unjailbroken state.

**Comment by kidiron08** [comment]
It works now
