### ISSUE TITLE
Make compatible with Scarlet

### ISSUE THREAD

**Issue by Legend7269** [PojavLauncherTeam/PojavLauncher_iOS#477]
### Describe the request.

Can you make this compatible with scarlet. Im on ios 16, I cant jailbreak, and altstore is not installing. If you want to find scarlet search uses.scarlet.

**Comment by Thebelg** [comment]
oh i have the same problem

**Comment by abhishekgi** [comment]
First intall esign ipa using scarlet Then import pojav launcher ipa in esign and click on unzip then click on payload then click on pojav launcher ipa and click on sign After signing complete click on install button that appears After that launcher will open butYou have to find a way to enable jit But make sure that before installing the pojav launcher with esign delete the existing pojav launcher

**Comment by crystall1nedev** [comment]
PojavLauncher does not support Scarlet because of how it uses enterprise certificates to sign apps. There is no way to get around this - use a different service to install PojavLauncher.


I removed abhishekgi’s comment because it referenced E-Sign - I could not verify that this was a legitimate application and found that it uses certificates that do not belong to the end user, and was commonly used to commit piracy.

**Comment by DeltaPv** [comment]
You can install it (but you need jit to play Minecraft)

1. Open scarlet
2. Install ipa
3. Go to files on my iPad then click on the scarlet folder
4. Click signed ipa it will send you to scarlet
5.  click install ipa then click sign ipa it will install
