### ISSUE TITLE
Running PojavLauncher without JIT

### ISSUE THREAD

**Issue by letsgoawaydev** [PojavLauncherTeam/PojavLauncher_iOS#482]
### Would it be possible to run PojavLauncher without jit?

I know it would be really slow, to the point of unplayability but would it be possible at all? Apps like UTM SE can run full Virtual Machines without JIT, albeit slowly. If you could run Pojav without jit it would be nice because you wouldn’t have to be on the same wifi when using AltStore. Or even have wifi at all.

**Comment by letsgoawaydev** [comment]
This would also make the Portability of Pojav much better considering you dont need to be at one place to use pojav

**Comment by artdeell** [comment]
The thing is that technically the JVM has the ability to run interpreted but it still doesn't work without a JIT enabler active. As an androud dev idk why it happens but it seems like iOS doesn't give the JVM enough permissions to set up the caches and stack.

**Comment by crystall1nedev** [comment]
There is no point in releasing a “no-JIT” copy of PojavLauncher for any iOS device, as still none have the power to drive it with reasonable performance. Portability doesn’t matter when the game is running at 2FPS on the newest hardware.

Comparing to UTM SE is invalid too - UTM SE *can* be slow because not everything you do in it is expected to be fast, say, using a Linux VM with no desktop environment. Given that we’re driving a desktop game on mobile hardware, it just doesn’t make sense.

**Comment by letsgoawaydev** [comment]
ok yeah that makes sense

**Comment by eTNTdiscord** [comment]
maybe u can like crank down the graphics and no need to use jit?

**Comment by Elbozo123** [comment]
No JIT trouble at the cost of graphics. Really, worth it

**Comment by Elbozo123** [comment]
Anyway how to do it?

**Comment by loafman-kangjun** [comment]
I thought that this should be needed, Anyone else doesn't like to Play MC on iPad with "M" CPU during their holiday?

**Comment by RiffleXReal-Games** [comment]
U can simply use your computer to use jit
