### ISSUE TITLE
[BUG] "Needs Firmware"

### ISSUE THREAD

**Issue by BattyBest** [PojavLauncherTeam/PojavLauncher_iOS#486]
### Describe the bug

I went to actions, get the latest dev build's .deb file and installed it using filza. The launcher itself worked fine, however (for some reason) the .deb needs "firmware" when it should be "iPhone Firmware (sbin)".

Sileo gets mad at this and refuses to let you do anything else.

### The log file and images/videos

N/A

### Steps To Reproduce

```markdown
1. Download pojavlauncher's latest .deb file
2. Install using your favorite file manager
3. Go to your favorite package manager, it should be mad at you because pojavlauncher is missing a dependency (and is also somehow installed)
```

### Expected Behavior

PojavLauncher should not have 'firmware' as a dependency, because lets be real, if your firmware is missing you have bigger problems.

### Platform

```markdown
- Device model: iPad 7,11
- CPU architecture: A10
- Jailbreak method: Palera1n, default
- Package manager: Sileo
- PojavLauncher version: Latest dev build (as of yesterday)
```

### Anything else?

This should be insanely easily to fix

**Comment by khanhduytran0** [comment]
You’re opening this issue in Android repo, iOS repo has a separate issue tracker.

Debian package will be removed in the near future, because of that there is AppSync updated for latest iOS 16.2, so you just grab ipa file and install in Filza.

In Debian package, `firmware` indicates minimum and maximum version. It is a virtual package, so it is invisible in Sileo, but visible in `apt search firmware$`:
```
firmware/now <your iOS version> all [installed,local]
  almost impressive Apple frameworks
```
On the other side, `firmware-sbin` has nothing to do with PojavLauncher, as it bundles various system utilities.

We have 2 separate Debian packages:
- Regular package, has maximum firmware version set to below iOS 15, as there is [a major breaking change starting from iOS 15](https://support.apple.com/guide/security/secd698747c9/web).
- Rootless package, for iOS 15+, but this has never been tested. Use at your own risk.
