### ISSUE TITLE
[Bug] <Zink seems to glitch out when rotating the screen>

### ISSUE THREAD

**Issue by Kinda-Stormy** [PojavLauncherTeam/PojavLauncher_iOS#603]
### Describe the bug

When ever rotating the screen while using the Zink renderer, it seems to just glitch out.

I tested this with Vanilla and Optifine

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12444377/latestlog.txt)
[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/12444378/latestlog.old.txt)

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/80485413/f8ad8c21-f165-4f8c-b3ae-b816521579f4

### Steps To Reproduce

```markdown
Start Minecraft with Zink renderer
Join a server or world
Rotate your screen
```

### Expected Behavior

Being able to play the game in the other orientation normally.

### Platform

```markdown
- Device model: iPad 6th Gen
- iOS version: 16.6
- PojavLauncher version: 3.0
```

**Comment by ToneXum** [comment]
How the hell did you get Zink running?

Anyways. When you rotate your screen the pixels on it rearange, wich Zink does not detect. The video perfectly demostrates how Zink drawn like 1,5 rows on what it thinks is one (because the rows get smaller when rotated wich makes them overlap).

Keep in mind that Zink is pretty new on iOS / iPadOS so if this is something you really dont want happening cosider using a different rendering engine (like ANGLE for Metal).

**Comment by Kinda-Stormy** [comment]
I am aware that it's new, I am just reporting issues to be fixed on iOS 16.

**Comment by ToneXum** [comment]
Zink Mesa is not maintained by the PojavLauncher Team, go report this issue there

**Comment by khanhduytran0** [comment]
> Zink Mesa is not maintained by the PojavLauncher Team, go report this issue here
> 
> https://gitlab.freedesktop.org/mesa/mesa/-/issues

Please no. They aren’t likely to support since mobile GPUs aren’t in their priority (unless it’s in Mesa like Adreno Turnip).
Those issues may be solved in the future, but no plan as of now because shaders do not work yet.

**Comment by Kinda-Stormy** [comment]
Alright then, that's fine.
