### ISSUE TITLE
[F-Req] Pojavlauncher with no jit

### ISSUE THREAD

**Issue by baechooYT** [PojavLauncherTeam/PojavLauncher_iOS#612]
### Is this request related to a bug?

It’s not related to a bug

### Describe the request.

There was same request: [Issue](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues/482#issue-1533124699) 

In that feature request [crystall1nedev](https://github.com/crystall1nedev)(dev of pojavlauncher) said the current performance of the iPhones cannot have the similar performance of the PCs.

But the A17 Pro has similar performance to the M1.
![IMG_0069](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/66154521/6e1b74cf-1354-4cc7-a978-d6062bfe7ec4)
So I think it could able to run Minecraft JE without an issue.

**Comment by artdeell** [comment]
The issue with running without just is not so much the raw power. The issue is that without JIT, Java has to resort to running in interpreted mode. Java's interpreted mode is, like, very slow. Like, unfathomably slow. If you had 120 fps with JIT, on pure interpreted mode you'd get, like, 25, or maybe 10, or 5. Basically, it would be an unpleasant experience.
Making it faster is not much of an option, because that would require implementing a custom JVM whose main purpose is running in the interpreted mode, and that is an enormous undertaking that will take a huge amount of (unpaid) development time that could be used to improve the launcher itself.
If you want to check out how good MC will run without JIT, just add `-Xint` in your JVM arguments and see for yourself.

**Comment by crystall1nedev** [comment]
To add on:

This year’s iPhone does have the performance of an M1 Mac. M1 Macs run the game at about 4-10FPS when in interpreted mode.
