### ISSUE TITLE
Jit on iPhone without any app

### ISSUE THREAD

**Issue by AASHIRWADGAMINGXD** [PojavLauncherTeam/PojavLauncher_iOS#651]
### Add some background

How to download Jit poja launcher

### Time to document.

Fix

### Disclaimers

Fix

**Comment by Zhou-Shilin** [comment]
You can't open the JIT without the app unless you use XCode/AltServer on your computer. but if you use XCode/AltServer, you have to use your computer every time you need to open the Pojavlauncher. A better solution is to use [TrollStore](https://github.com/opa334/TrollStore/releases) or [SideStore](https://sidestore.io/). Also, you should [submit this issue as a question](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues/new?assignees=&labels=question&projects=&template=question.yml&title=%5BQuestion%5D+%3CShort+description%3E) rather than documentation.

**Comment by ItAnthon** [comment]
@AASHIRWADGAMINGXD  “JIT” isn’t something that you download. “JIT” is a debugger that you’re supposed to enable to make PojavLauncher actually playable. You can enable this debugger but looking at the documentation at: https://pojavlauncherteam.github.io/

it covers pretty much any way to enable the debugger.
