### ISSUE TITLE
Unable to login with Microsoft account

### ISSUE THREAD

**Issue by pythonr0ck** [PojavLauncherTeam/PojavLauncher_iOS#654]
### Describe the bug

PojavLauncher crashes upon acquiring XSTS when trying to login with a Microsoft account. I’ve tried uninstalling and reinstalling PojavLauncher but the issue still persists.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/14397081/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login with Microsoft account
```

### Expected Behavior

I expect Pojav to log me into my account.

### Platform

```markdown
- Device model: iPad (9th generation)
- iOS version: iPadOS 16.1.1 (TrollStore)
- PojavLauncher version: 3.0-development from build 1151
```

**Comment by GaucovyAero** [comment]
try logging into minecraft.net

**Comment by pythonr0ck** [comment]
> try logging into minecraft.net

It still crashes on XSTS

**Comment by GaucovyAero** [comment]
weird

**Comment by ItAnthon** [comment]
Before trying out my possible solution: **please backup everything you care about on PojavLauncher**
Since you have TrollStore, that means you have Filza (if you don’t please get it its useful) Open Filza, go to: var/mobile/Containers/Data/Application (scroll until you find PojavLauncher) and delete its folder.

open PojavLauncher as normal and it should just work.

if you haven’t already please get the latest GitHub actions version of PojavLauncher

**Comment by pythonr0ck** [comment]
Deleting Pojav in filza doesn't work, but it seems like downgrading to v2.2 actually fixes the problem. Instead of crashing, it just shows an error about my account. After fixing and updating it, it works. Did this a long while ago, but forgot to close the issue, so I'm doing that now.
