### ISSUE TITLE
[Question] <Short description> I may sound stupid because I don't know anything but is it possible to make a version where you can run it on Scarlet?

### ISSUE THREAD

**Issue by Legend727** [PojavLauncherTeam/PojavLauncher_iOS#694]
### Ask the question here.

I cant get troll-store or get a jailbreak and its really annoying to plug in your phone into a computer. Why cant I just sideload it with something like Scarlet or just put it on the app store somehow? It might be possible since they allowed the Delta emulator on there.

**Comment by Kiokingz** [comment]
no because, PojavLauncher runs with a tech called "JIT", its a fast-translator that makes PojavLauncher runs with great performance, it cannot be regularly enabled normally and can only be enabled via connection to a PC, trollstore doesn't because it abuses a bug called "CT" (CoreTrust) which forces ios to give special permisions, and that includes enabling JIT. and Scarlet doesn't allow JIT, making it not possible to launch minecraft java on pojavlauncher.
