### ISSUE TITLE
[Question] Can’t play any version.

### ISSUE THREAD

**Issue by manteroid** [PojavLauncherTeam/PojavLauncher_iOS#695]
### Ask the question here.

I downloaded the “latest” Pojavlauncher (3.0 it says) but I am unable to play any version. All it says is (Default) for the versions and when I try to play on (Default), all it tells me is, “Error: The file ‘Unknown.json’ couldn’t be opened because there is no such file.” What do I do? I’ve tried to download other versions but only Deepslate 2.2 works and even then I can’t open anything beyond 1.20.

**Comment by Kiokingz** [comment]
you're supposed to create a minecraft profile version, the "default" one is null

**Comment by manteroid** [comment]
> you're supposed to create a minecraft profile version, the "default" one is null

excuse my dumbass, but what do you mean create a minecraft profile version?

**Comment by Kiokingz** [comment]
> > you're supposed to create a minecraft profile version, the "default" one is null
> 
> excuse my dumbass, but what do you mean create a minecraft profile version?

oh about that, since you're on v3.0, you should have this button in the attached picture.
![IMG_2889](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/142306553/102060aa-580b-4ff1-a9b5-ea1db6ae0bcf)

once you pressed that, press the "+" button near the top-right corner, or i say beside your minecraft skin profile.
![1244288471791833169remix-1716731958726](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/142306553/6ab334de-74a7-4edd-9c99-f6a3220c832a)

after that, a prompt will appear, giving you options, installing mod loaders will be the same process like normal minecraft do, except use the dedicated mod loader installer in the prompt where i previously mentioned, instead downloading universal jar like fabric do: 
![image](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/142306553/979e369f-de66-4dc2-be8c-63fe316204c1)

**Comment by manteroid** [comment]
thank you so much dude, this helped a lot!!
final stupid question: how do i install sodium into this?

**Comment by Kiokingz** [comment]
> thank you so much dude, this helped a lot!! final stupid question: how do i install sodium into this?

sodium is pretty much unsupported and likely will never be supported, somewhat vanilla performs better without sodium somehow.

**Comment by manteroid** [comment]
shit alright, just asked cause there aint no optifine on 1.20.6 atm lmao, thanks tho
