### ISSUE TITLE
How to walk while sneaking?

### ISSUE THREAD

**Issue by IvanKulagin** [PojavLauncherTeam/PojavLauncher_iOS#98]
The only way for walking on sneak is to press sneak and forward keys with two fingers, which is not very comfortable to do. I think you should make sneak key a toggle or add an ability to drag your finger from sneak key to the forward key with sneak key remain pressed

**Comment by khanhduytran0** [comment]
Maybe..:eyes:

**Comment by IvanKulagin** [comment]
I've just found out that you can set sneak to toggle in accessibility settings. This can be used as a fix for now

**Comment by Doregon** [comment]
There’s another option which sort of works, although it’s a glitch, and works with any button:

1) Start by holding down the button you wish to “toggle”. Take note of how the button gets **slightly darker**.

2) Swipe up until the button returns to its normal brightness (all the way to the top of the screen works as well)

3) Because you never let go, the game will think you’re still holding down that button even when you’re not. Tap the button again to un-hold.

**Comment by khanhduytran0** [comment]
With v2.0, it is now possible to set a button to toggle-able mode in custom controls, so you can enable this for the sneak button.
